### ISSUE TITLE
Following your Tut

### ISSUE THREAD

**Issue by lesreaper** [lukas/robot#5]
I spent the $1100 (I got a GTX 1070 w/ 8 GB) based on your tut here: https://www.linuxdevcenter.com/learning/build-a-super-fast-deep-learning-machine-for-under-1000

I'm not doing a robot, just a straight feed via nginx and gunicorn from a Pi.

I can't seem to get Yolo and Darknet working together no matter what I try, including your directions here. Darknet doesn't seem to like the image sequence the Pi is producing from http://192.168.1.xx/cam.jpg (which is constantly being overwritten) using this command:

./darknet detector test cfg/coco.data cfg/yolo.cfg yolo.weights http://192.168.1.xx/cam.jpg 

Do you have any ideas?

**Comment by lukas** [comment]
Totally fair question but this a different github project - would you mind posting on stackoverflow or something like that so people can find this answer?

Anyway, you need to modify demo.c in darknet to reopen when the stream gets closed:
```
-        error("Stream closed.");
+       printf("Stream closed, reopening.\n");
+        cap = cvCaptureFromFile(fname);
+       in = get_image_from_stream(cap);
+        //error("Stream closed.");
```

**Comment by lesreaper** [comment]
It doesn't work this way either. It just gives me a black image. Works fine when I run it on the demo. 

I also created a Stack question here: http://stackoverflow.com/questions/42824871/get-raspberry-pi-camera-feed-into-darknet-and-yolo

If I update the demo.h as you suggest, I get a:

`video file: http://192.168.1.xx/cam.jpg
Stream closed.: Operation now in progress
darknet: ./src/utils.c:193: error: Assertion `0' failed.`
